[WIP] templates, mock data
htmlacademy-ecmascript/892167-big-trip-13 pull request #5
Opened 2020-11-30 12:07 UTC by Barnicle

2020-12-02 14:09 UTC, Dima-Dim requested changes
Нужно поправить let-ы, там где они в итоге не меняются.

2020-12-02 14:09 UTC, Dima-Dim commented on src/view/tripInfo.js
> +    totalPrice += data[key].price;
reduce для этого интереснее :)

2020-12-02 18:04 UTC, Barnicle commented on src/view/tripInfo.js
> +    totalPrice += data[key].price;
поправил)

2020-12-03 09:57 UTC, Barnicle commented on src/mock/tripPoint.js
> +  let images = [];
да, исправил

2020-12-04 04:43 UTC, Dima-Dim reviewed
Хорошо.
Если поправишь подключение сттелей, то тут https://htmlacademy-ecmascript.github.io/892167-big-trip-13/5/ на это будет удобнее смотреть.

2020-12-04 04:43 UTC, Dima-Dim commented on src/main.js
> +const testData = generateTripPointData(3);
3 в данном случае магическое число.

2020-12-04 04:43 UTC, merged